version: "3.2"
services:
  node-dev:
    container_name: node-dev
    hostname: node-dev
    build: ./
    image: node-dev:latest
    volumes:
      - type: bind
        source: .
        target: /app/
    environment:
      - DEBUG_DOCKER_SETUP=1
